version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    volumes:
      - /home/noby.ardor/hadoop/docker-kafka/data/zk/data:/var/lib/zookeeper/data
      - /home/noby.ardor/hadoop/docker-kafka/data/zk/log:/var/lib/zookeeper/log
    env_file:
      - ./zookeeper.env
    ports:
      - 22181:2181
  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    volumes:
      - /home/noby.ardor/hadoop/docker-kafka/data/kafka:/var/lib/kafka/data
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    env_file:
      - ./kafka.env
  rest-proxy:
    image: confluentinc/cp-kafka-rest:latest
    ports:
      - 8082:8082
    hostname: rest-proxy
    container_name: rest-proxy
    depends_on:
      - broker
    env_file:
      - ./kafka.env